### ISSUE TITLE
Create is_php method in BaseSignature

### ISSUE THREAD

**Issue by sggottlieb** [sggottlieb/cmfieldguide#3]
This method will use the expose_php easter egg (credits page) to tell if a page is definitely being served by PHP.  

Here is the information behind:

http://www.pc-freak.net/blog/disable-php-expose-disable-php-credits-page-showing-up-with-including-some-phpphpb8b5f2a0-3c92-11d3-a3a9-4c7b08c10000-variable-to-a-php-powered-webserver/

**Comment by deanebarker** [comment]
We can do this, but it's hard to make it definitive.  The problem is that you have to hit a URL _that invokes PHP_.  This means hitting a specific .php page, or hitting a site that wildcards the PHP engine or rewrites everything to a PHP page.

So, just to confirm, the idea is to return a confirmed positive, if it does return, but not a confirmed negative if it doesn't, right?

**Comment by sggottlieb** [comment]
You got it.  I think if we hit the root of the site, that should be picked up by some index.php script or some url rewrite that goes to an index.php.  If we see that credits page, we know it is PHP.  If we don't we don't know anything.
